package org.wlcg.storage.api.model.error;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * RFC 7807
 * {
    "type": "https://example.com/probs/out-of-credit",
    "title": "You do not have enough credit.",
    "detail": "Your current balance is 30, but that costs 50.",
    "instance": "/account/12345/msgs/abc",
    "balance": 30,
    "accounts": ["/account/12345",
                 "/account/67890"]
   }
 *
 */
@Schema(description = "Error object: aligned with RFC 7807")
public class ErrorModel {

  @Schema(description = "A URI reference that identifies the problem type This specification encourages that, when dereferenced, it provide human-readable documentation "
  		+ "for the problem type (e.g., using HTML).  When this member is not present, its value is assumed to be \"about:blank\".", required = true)
  private String type = "about:blank";
  
  @Schema(description = "A short, human-readable summary of the problem type", required = true)
  private String title;

  @Schema(description = "The HTTP status code generated by the origin server for this occurrence of the problem.", required = true)
  int status;
  
  @Schema(description = "A human-readable explanation specific to this occurrence of the problem.")
  String detail;
  
  public ErrorModel() {
    
  }
  
  
  public ErrorModel(String type, String title, int status, String detail) {
    this.type = type;
    this.title = title;
    this.status = status;
    this.detail = detail;
  }

  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public int getStatus() {
    return status;
  }

  public void setStatus(int status) {
    this.status = status;
  }

  public String getDetail() {
    return detail;
  }

  public void setDetail(String detail) {
    this.detail = detail;
  }  
}
